### ISSUE TITLE
logging error

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#358]
```
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/aih/xudong.sun/domainlab_dial/main_out.py", line 17, in <module>
    exp.execute()
  File "/home/aih/xudong.sun/domainlab_dial/domainlab/compos/exp/exp_main.py", line 65, in execute
    flag_stop = self.trainer.tr_epoch(epoch)
  File "/home/aih/xudong.sun/domainlab_dial/domainlab/algos/trainers/train_fbopt.py", line 100, in tr_epoch
    flag_stop = self.observer.update(epoch)  # FIXME: should count how many epochs were used
  File "/home/aih/xudong.sun/domainlab_dial/domainlab/algos/observers/c_obvisitor_cleanup.py", line 19, in update
    return self.observer.update(epoch)
  File "/home/aih/xudong.sun/domainlab_dial/domainlab/algos/observers/b_obvisitor.py", line 53, in update
    if self.model_sel.update():
  File "/home/aih/xudong.sun/domainlab_dial/domainlab/algos/msels/c_msel_oracle.py", line 32, in update
    return self.msel.update()
  File "/home/aih/xudong.sun/domainlab_dial/domainlab/algos/msels/c_msel_val.py", line 33, in update
    logger.debug("early stop counter: ", self.es_c)
Message: 'early stop counter: '
Arguments: (1,)
--- Logging error ---
Traceback (most recent call last):
  File "/home/aih/xudong.sun/anaconda3/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/home/aih/xudong.sun/anaconda3/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/home/aih/xudong.sun/domainlab_dial/domainlab/compos/exp/exp_main.py", line 65, in execute
    if self.model_sel.update():

```

**Comment by smilesun** [comment]
https://github.com/marrlab/DomainLab/pull/357
