### ISSUE TITLE
bug in fbopt

### ISSUE THREAD

**Issue by Car-la-F** [marrlab/DomainLab#411]
I found a bug at `commit a9054e39e4015b11463dbfd6b83b722cf467ae2f`

```
at epoch 11, before shooting: epo_reg_loss=[32060120.125, -10529.612976074219, 0.0, -1372944.59375, 47.09081554412842],                  epo_task_loss=1047.217529296875
at epoch 11, after shooting: epo_reg_loss=[31488001.75, -8841.112701416016, 0.0, -1476452.640625, 52.12630653381348],                 epo_task_loss=1056.2708740234375
at epoch 11, after \bar \theta: epo_reg_loss=[31500170.875, -8747.40625, 0.0, -1472937.1875, 48.304492473602295],                 epo_task_loss=1056.2708740234375
!!!!found free descent operator, update setpoint to [31500170.875, -8747.40625, 0.0, -1472937.1875, 48.304492473602295]
Traceback (most recent call last):
  File "C:\Users\CarlaFeistner\Documents\DomainLab\main_out.py", line 17, in <module>
    exp.execute()
  File "C:\Users\CarlaFeistner\Documents\DomainLab\domainlab\compos\exp\exp_main.py", line 65, in execute
    flag_stop = self.trainer.tr_epoch(epoch)
  File "C:\Users\CarlaFeistner\Documents\DomainLab\domainlab\algos\trainers\train_fbopt.py", line 187, in tr_epoch
    self.hyper_scheduler.reg_lower_bound_as_setpoint = self.hyper_scheduler.coeff_ma * epo_reg_loss + (1-self.hyper_scheduler.coeff_ma)* self.hyper_scheduler.reg_lower_bound_as_setpoint
TypeError: can't multiply sequence by non-int of type 'float'
```

**Comment by drEast** [comment]
`self.hyper_scheduler.coeff_ma * epo_reg_loss `
multiplies python list to scalar. Circumwented it by converting epo_reg_loss to torch tensor, do the calculation of this line and the convert back to list.
Solved by 7d71982
