### ISSUE TITLE
matchdg broken on master

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#449]
```
python main_out.py --te_d=caltech --task=mini_vlcs --debug --bs=2 --aname=matchdg --epochs_ctr=3 --epos=6 --nname=alexnet
+ python main_out.py --te_d=caltech --task=mini_vlcs --debug --bs=2 --aname=matchdg --epochs_ctr=3 --epos=6 --nname=alexnet



no algorithm conf specified, going to use default



/home/runner/work/DomainLab/DomainLab/domainlab/arg_parser.py:239: UserWarning: no algorithm conf specified, going to use default
  warnings.warn("no algorithm conf specified, going to use default")
reading domain: sun
list of subfolders ['sapiens', 'flying', 'vehicle', 'sofa', 'dog']
reading domain: labelme
list of subfolders ['husky', 'sit', 'bird', 'drive']
reading domain: caltech
list of subfolders ['stuhl', 'mensch', 'hund', 'auto', 'vogel']

using device: cpu

/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
original alex net out dim 1000
re-initialized to 2
/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/torch/nn/_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `AUROC` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
b'0420c90'
model name: debug_mini_vlcs_te_caltech_matchdg_b0420c90_2023md_09md_22_15_10_24_seed_0

 Experiment start at: 2023-09-22 15:10:24.197225
for class chair bigest sample size is 7 ref domain is labelme
for class car bigest sample size is 14 ref domain is labelme
for class 0
domain index as base domain: 1
Base Domain size 7
for class 1
domain index as base domain: 1
Base Domain size 14
Total Label MisMatch across pairs: 0
torch.Size([21, 2, 3, 224, 224]) torch.Size([21, 2, 1])
self.str_phase 0 epoch
number of batches in match tensor: 11
single batch match tensor size: torch.Size([2, 2, 3, 224, 224])
--- Logging error ---
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/runner/work/DomainLab/DomainLab/main_out.py", line 17, in <module>
    exp.execute()
  File "/home/runner/work/DomainLab/DomainLab/domainlab/compos/exp/exp_main.py", line 62, in execute
    self.trainer.before_tr()
  File "/home/runner/work/DomainLab/DomainLab/domainlab/algos/trainers/train_matchdg.py", line 34, in before_tr
    ctr.train()
  File "/home/runner/work/DomainLab/DomainLab/domainlab/algos/compos/matchdg_ctr_erm.py", line 42, in train
    self.tr_epoch(epoch)
  File "/home/runner/work/DomainLab/DomainLab/domainlab/algos/compos/matchdg_ctr_erm.py", line 76, in tr_epoch
    self.update_batch(epoch, batch_idx, x_e, y_e, d_e)
  File "/home/runner/work/DomainLab/DomainLab/domainlab/algos/compos/matchdg_ctr_erm.py", line 195, in update_batch
    logger.debug(f'class {y_c} with same class and different class: ',
Message: 'class 0 with same class and different class: '
Arguments: ('1 1',)
--- Logging error ---
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/runner/work/DomainLab/DomainLab/main_out.py", line 17, in <module>
    exp.execute()
  File "/home/runner/work/DomainLab/DomainLab/domainlab/compos/exp/exp_main.py", line 62, in execute
    self.trainer.before_tr()
  File "/home/runner/work/DomainLab/DomainLab/domainlab/algos/trainers/train_matchdg.py", line 34, in before_tr
    ctr.train()
  File "/home/runner/work/DomainLab/DomainLab/domainlab/algos/compos/matchdg_ctr_erm.py", line 42, in train
    self.tr_epoch(epoch)
  File "/home/runner/work/DomainLab/DomainLab/domainlab/algos/compos/matchdg_ctr_erm.py", line 76, in tr_epoch
    self.update_batch(epoch, batch_idx, x_e, y_e, d_e)
  File "/home/runner/work/DomainLab/DomainLab/domainlab/algos/compos/matchdg_ctr_erm.py", line 195, in update_batch
    logger.debug(f'class {y_c} with same class and different class: ',
Message: 'class 0 with same class and different class: '
Arguments: ('1 1',)
```

**Comment by smilesun** [comment]
TypeError: not all arguments converted during string formatting                                                                                                                                                                                                                           
Call stack:                                                                                                                                                                                                                                                                               
  File "/home/sunxd/domainlab/main_out.py", line 17, in <module>                                                                                                                                                                                                                          
    exp.execute()                                                                                                                                                                                                                                                                         
  File "/home/sunxd/domainlab/domainlab/compos/exp/exp_main.py", line 68, in execute                                                                                                                                                                                                      
    flag_stop = self.trainer.tr_epoch(epoch)                                                                                                                                                                                                                                              
  File "/home/sunxd/domainlab/domainlab/algos/trainers/train_matchdg.py", line 48, in tr_epoch                                                                                                                                                                                            
    self.erm.tr_epoch(epoch)                                                                                                                                                                                                                                                              
  File "/home/sunxd/domainlab/domainlab/algos/compos/matchdg_ctr_erm.py", line 76, in tr_epoch                                                                                                                                                                                            
    self.update_batch(epoch, batch_idx, x_e, y_e, d_e)                                                                                                                                                                                                                                    
  File "/home/sunxd/domainlab/domainlab/algos/compos/matchdg_ctr_erm.py", line 195, in update_batch                                                                                                                                                                                       
    logger.debug(f'class {y_c} with same class and different class: ',                                                                                                                                                                                                                    
Message: 'class 0 with same class and different class: '                                                                                                                                                                                                                                  
Arguments: ('0 2',)                                                                                                                                                                                                                                                                       
--- Logging error ---                                                                                                                                                                                                                                                                     
Traceback (most recent call last):                                                                                                                                                                                                                                                        
  File "/home/sunxd/anaconda3/lib/python3.9/logging/__init__.py", line 1083, in emit                                                                                                                                                                                                      
    msg = self.format(record)                                                                                                                                                                                                                                                             
  File "/home/sunxd/anaconda3/lib/python3.9/logging/__init__.py", line 927, in format                                                                                                                                                                                                     
    return fmt.format(record)                                                                                                                                                                                                                                                             
  File "/home/sunxd/anaconda3/lib/python3.9/logging/__init__.py", line 663, in format                                                                                                                                                                                                     
    record.message = record.getMessage()                                                                                                                                                                                                                                                  
  File "/home/sunxd/anaconda3/lib/python3.9/logging/__init__.py", line 367, in getMessage                                                                                                                                                                                                 
    msg = msg % self.args                                                                                                                                                                                                                                                                 
TypeError: not all arguments converted during string formatting                                                                                                                                                                                                                           
Call stack:
