### ISSUE TITLE
bug with phase plot

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#639]
```
Traceback (most recent call last):                                                                                                                                                                                 
  File "/home/sunxd/a_helm_home/pacs_diva_full/domainlab/utils/generate_fbopt_phase_portrait.py", line 174, in <module>                                                                                            
    phase_portrait_combined(event_files, colors,                                                                                                                                                                   
  File "/home/sunxd/a_helm_home/pacs_diva_full/domainlab/utils/generate_fbopt_phase_portrait.py", line 71, in phase_portrait_combined                                                                              
    xy_dist = np.sqrt((x[i + 1] - x[i])**2 + (y[i + 1] - y[i])**2)                                                                                                                                                 
IndexError: list index out of range                                                                                                                                                                                
Using the following tensorboard event files:                                                                            
```

**Comment by smilesun** [comment]
@agisga , any progress?

**Comment by agisga** [comment]
I think this is resolved with the commits since the issue was created? Do you still see this error?

**Comment by smilesun** [comment]
We run via (no need to stop)

`sh run_fbopt_mnist_diva_autoki.sh
`
then I run 

sh script_generate_all_figures_diva.sh
```

Using the following tensorboard event files:
runs/Feb01_15-25-36_sunxd-ThinkPad-P1-Gen-4i/events.out.tfevents.1706797536.sunxd-ThinkPad-P1-Gen-4i.26864.0
Event file runs/Feb01_15-25-36_sunxd-ThinkPad-P1-Gen-4i/events.out.tfevents.1706797536.sunxd-ThinkPad-P1-Gen-4i.26864.0 -- available plots:
['dyn_mu/beta_d', 'controller_gain/beta_d', 'delta/beta_d', 'dyn_mu/beta_y', 'controller_gain/beta_y', 'delta/beta_y', 'dyn_mu/beta_x', 'controller_gain/beta_x', 'delta/beta_x', 'dyn_mu/gamma_d', 'controller_gain/gamma_d', 'delta/gamma_d', 'dyn_mu/mu_recon', 'controller_gain/mu_recon', 'delta/mu_recon', 'lossrd/dyn_mu_recon', 'lossrs/setpoint_mu_recon', 'x_ell_y_r/loss_mu_recon', 'lossrd/dyn_beta_d', 'lossrs/setpoint_beta_d', 'x_ell_y_r/loss_beta_d', 'lossrd/dyn_beta_x', 'lossrs/setpoint_beta_x', 'x_ell_y_r/loss_beta_x', 'lossrd/dyn_beta_y', 'lossrs/setpoint_beta_y', 'x_ell_y_r/loss_beta_y', 'lossrd/dyn_gamma_d', 'lossrs/setpoint_gamma_d', 'x_ell_y_r/loss_gamma_d', 'loss_task/penalized', 'loss_task/ell', 'acc/te', 'acc/val', 'acc/sel', 'acc/setpoint']
script_generate_all_figures_diva.sh: 28: Syntax error: "(" unexpected
```

**Comment by smilesun** [comment]
@agisga

**Comment by agisga** [comment]
> script_generate_all_figures_diva.sh: 28: Syntax error: "(" unexpected

@smilesun  This error doesn't appear when I run `bash script_generate_all_figures_diva.sh`, i.e. `bash` instead of `sh` (I think bash is a superset of sh).
Can you try running with `bash`?
Seems that it works that way. Here is an example plot I just generated:

![image](https://github.com/marrlab/DomainLab/assets/11449372/77da5034-a9a4-4c32-bd13-3a2078f0617b)
