### ISSUE TITLE
botocore not defined

### ISSUE THREAD

**Issue by smilesun** [marrlab/DomainLab#788]
```
snakemake --rerun-incomplete --cores 1 -s "domainlab/exp_protocol/benchmark.smk" --configfile "$CONFIGFILE" --keep-going --summary  # this will give us a clue first what jobs will be run
+ snakemake --rerun-incomplete --cores 1 -s domainlab/exp_protocol/benchmark.smk --configfile examples/benchmark/demo_shared_hyper_grid.yaml --keep-going --summary
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/snakemake/__init__.py", line 672, in snakemake
    workflow.include(
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/snakemake/workflow.py", line 1363, in include
    snakefile = infer_source_file(snakefile, basedir)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/snakemake/sourcecache.py", line 323, in infer_source_file
    if is_local_file(path_or_uri):
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/snakemake/common/__init__.py", line 92, in is_local_file
    return parse_uri(path_or_uri).scheme == "file"
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/snakemake/common/__init__.py", line 96, in parse_uri
    from smart_open import parse_uri
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/smart_open/__init__.py", line 34, in <module>
    from .smart_open_lib import open, parse_uri, smart_open, register_compressor  # noqa: E402
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/smart_open/smart_open_lib.py", line 35, in <module>
    from smart_open import doctools
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/smart_open/doctools.py", line 21, in <module>
    from . import transport
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/smart_open/transport.py", line 104, in <module>
    register_transport("smart_open.s3")
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/smart_open/transport.py", line 49, in register_transport
    submodule = importlib.import_module(submodule)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/smart_open/s3.py", line 121, in <module>
    RETRY = Retry()
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/smart_open/s3.py", line 86, in __init__
    self.exceptions: List[Exception] = [botocore.exceptions.EndpointConnectionError]
NameError: name 'botocore' is not defined
Error: Process completed with exit code 1.
```

**Comment by smilesun** [comment]
it seems re-run the CI fixed the problem?
